### PR TITLE
Add celestia proto files

### PR DESCRIPTION
**Pull request by rach-id**
Adds celestia proto files to the spec.
This branch is based on: https://github.com/celestiaorg/spec/pull/2 and also contains https://github.com/celestiaorg/spec/pull/1

https://github.com/celestiaorg/spec/pull/2 will need to be merged before mergin this one.

### CODE REVIEW

**Comment by evan-forbes** [comment]
waiting for #2 to be merged, so I that we can easily see the diff for this PR

**Comment by evan-forbes** [comment]
might need to rebase on master to so that the diffs from #2 aren't here as well

**Comment by rach-id** [comment]
Sure. After merging the other PR, I will cleanup

**Review by evan-forbes — COMMENTED** [review]
let's figure out why the linter is failing, and then merge! 

nice work :+1:

**Comment by rach-id** [comment]
@evan-forbes CI fixed

**Review by evan-forbes — APPROVED** [review]
awesome! :rocket:

**Pull request merged**
